name: Update WakaTime stats in README

permissions:          # ← add this
  contents: write     # allow the Action to commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}

          SHOW_TOTAL:   true
          TIME_RANGE:   all_time
          LANG_COUNT:   3
          BLOCKS:       "░▒▓█"
          STOP_AT_OTHER: true
