\name: Update WakaTime stats in README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          # ←  do not paste the key; pull it from the secrets context
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}   # commits back

          SHOW_TOTAL:   true
          TIME_RANGE:   all_time
          LANG_COUNT:   3
          BLOCKS:       "░▒▓█"
          STOP_AT_OTHER: true
          
